CREATE TABLE Manu 
(
    Manu_id	INT,
    Manu_name	VARCHAR(512),
    Nationality	VARCHAR(512)
);

INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('1', 'McLaren', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('2', 'BMW Sauber', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('3', 'Williams', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('4', 'Renault', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('5', 'Toro Rosso', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('6', 'Ferrari', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('7', 'Toyota', 'Japanese');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('8', 'Super Aguri', 'Japanese');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('9', 'Red Bull', 'Austrian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('10', 'Force India', 'Indian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('11', 'Honda', 'Japanese');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('12', 'Spyker', 'Dutch');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('13', 'MF1', 'Russian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('14', 'Spyker MF1', 'Dutch');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('15', 'Sauber', 'Swiss');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('16', 'BAR', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('17', 'Jordan', 'Irish');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('18', 'Minardi', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('19', 'Jaguar', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('20', 'Prost', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('21', 'Arrows', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('22', 'Benetton', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('23', 'Brawn', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('24', 'Stewart', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('25', 'Tyrrell', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('26', 'Lola', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('27', 'Ligier', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('28', 'Forti', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('29', 'Footwork', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('30', 'Pacific', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('31', 'Simtek', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('32', 'Team Lotus', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('33', 'Larrousse', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('34', 'Brabham', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('35', 'Dallara', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('36', 'Fondmetal', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('37', 'March', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('38', 'Andrea Moda', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('39', 'AGS', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('40', 'Lambo', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('41', 'Leyton House', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('42', 'Coloni', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('44', 'Euro Brun', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('45', 'Osella', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('46', 'Onyx', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('47', 'Life', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('48', 'Rial', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('49', 'Zakspeed', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('50', 'RAM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('51', 'Alfa Romeo', 'Swiss');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('52', 'Spirit', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('53', 'Toleman', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('54', 'ATS', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('55', 'Theodore', 'Hong Kong');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('56', 'Fittipaldi', 'Brazilian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('57', 'Ensign', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('58', 'Shadow', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('59', 'Wolf', 'Canadian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('60', 'Merzario', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('61', 'Kauhsen', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('62', 'Rebaque', 'Mexican');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('63', 'Surtees', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('64', 'Hesketh', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('65', 'Martini', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('66', 'BRM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('67', 'Penske', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('68', 'LEC', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('69', 'McGuire', 'Australian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('70', 'Boro', 'Dutch');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('71', 'Apollon', 'Swiss');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('72', 'Kojima', 'Japanese');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('73', 'Parnelli', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('74', 'Maki', 'Japanese');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('75', 'Embassy Hill', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('76', 'Lyncar', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('77', 'Trojan', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('78', 'Amon', 'New Zealander');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('79', 'Token', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('80', 'Iso Marlboro', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('81', 'Tecno', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('82', 'Matra', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('83', 'Politoys', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('84', 'Connew', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('85', 'Bellasi', 'Swiss');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('86', 'De Tomaso', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('87', 'Cooper', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('88', 'Eagle', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('89', 'LDS', 'South African');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('90', 'Protos', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('91', 'Shannon', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('92', 'Scirocco', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('93', 'RE', 'Rhodesian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('94', 'BRP', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('95', 'Porsche', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('96', 'Derrington', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('97', 'Gilby', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('98', 'Stebro', 'Canadian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('99', 'Emeryson', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('100', 'ENB', 'Belgian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('101', 'JBW', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('102', 'Ferguson', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('103', 'MBM', 'Swiss');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('104', 'Behra-Porsche', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('105', 'Maserati', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('106', 'Scarab', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('107', 'Watson', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('108', 'Epperly', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('109', 'Phillips', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('110', 'Lesovsky', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('111', 'Trevis', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('112', 'Meskowski', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('113', 'Kurtis Kraft', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('114', 'Kuzma', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('115', 'Christensen', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('116', 'Ewing', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('117', 'Aston Martin', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('118', 'Vanwall', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('119', 'Moore', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('120', 'Dunn', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('121', 'Elder', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('122', 'Sutton', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('123', 'Fry', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('124', 'Tec-Mec', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('125', 'Connaught', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('126', 'Alta', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('127', 'OSCA', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('128', 'Gordini', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('129', 'Stevens', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('130', 'Bugatti', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('131', 'Mercedes', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('132', 'Lancia', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('133', 'HWM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('134', 'Schroeder', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('135', 'Pawl', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('136', 'Pankratz', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('137', 'Arzani-Volpini', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('138', 'Nichels', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('139', 'Bromme', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('140', 'Klenk', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('141', 'Simca', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('142', 'Turner', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('143', 'Del Roy', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('144', 'Veritas', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('145', 'BMW', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('146', 'EMW', 'East German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('147', 'AFM', 'German');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('148', 'Frazer Nash', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('149', 'Sherman', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('150', 'Deidt', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('151', 'ERA', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('152', 'Aston Butterworth', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('153', 'Cisitalia', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('154', 'Talbot-Lago', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('155', 'Hall', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('156', 'Marchese', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('157', 'Langley', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('158', 'Rae', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('159', 'Olson', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('160', 'Wetteroth', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('161', 'Adams', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('162', 'Snowberger', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('163', 'Milano', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('164', 'HRT', 'Spanish');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('167', 'Cooper-Maserati', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('166', 'Virgin', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('168', 'Cooper-OSCA', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('169', 'Cooper-Borgward', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('170', 'Cooper-Climax', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('171', 'Cooper-Castellotti', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('172', 'Lotus-Climax', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('173', 'Lotus-Maserati', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('174', 'De Tomaso-Osca', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('175', 'De Tomaso-Alfa Romeo', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('176', 'Lotus-BRM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('177', 'Lotus-Borgward', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('178', 'Cooper-Alfa Romeo', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('179', 'De Tomaso-Ferrari', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('180', 'Lotus-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('181', 'Brabham-BRM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('182', 'Brabham-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('183', 'Brabham-Climax', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('184', 'LDS-Climax', 'South African');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('185', 'LDS-Alfa Romeo', 'South African');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('186', 'Cooper-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('187', 'McLaren-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('188', 'McLaren-Serenissima', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('189', 'Eagle-Climax', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('190', 'Eagle-Weslake', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('191', 'Brabham-Repco', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('192', 'Cooper-Ferrari', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('193', 'Cooper-ATS', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('194', 'McLaren-BRM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('195', 'Cooper-BRM', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('196', 'Matra-Ford', 'French');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('197', 'BRM-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('198', 'McLaren-Alfa Romeo', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('199', 'March-Alfa Romeo', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('200', 'March-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('201', 'Lotus-Pratt &amp; Whitney', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('202', 'Shadow-Ford', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('203', 'Shadow-Matra', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('204', 'Brabham-Alfa Romeo', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('205', 'Lotus', 'Malaysian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('206', 'Marussia', 'Russian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('207', 'Caterham', 'Malaysian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('208', 'Lotus F1', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('209', 'Manor Marussia', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('210', 'Haas F1 Team', 'American');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('211', 'Racing Point', 'British');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('213', 'AlphaTauri', 'Italian');
INSERT INTO Manu (Manu_id, Manu_name, Nationality) VALUES ('214', 'Alpine F1 Team', 'French');
